### PR TITLE
Update library.json add platforms avr

### PR DESCRIPTION
**Pull request by ricardojlrufino**
This fix a bug in PlatformIO dependencies
platformio/platformio#814

### CODE REVIEW

**Comment by GreyGnome** [comment]
Thanks... I'll take a look at it.

**Comment by frdteknikelektro** [comment]
I think you should update the version as well. So platform IO can crawling your repo

**Comment by ricardojlrufino** [comment]
This can be merged ?

**Comment by GreyGnome** [comment]
Sorry, I've been away, working on other projects. I'm pulling this now.

**Review by GreyGnome — APPROVED** [review]
I believe "atmelavr" needs a comma after it, which I've added.

**Comment by GreyGnome** [comment]
Merged, committed, and pushed.

**Comment by frdteknikelektro** [comment]
@GreyGnome I think you should also change the version. The version in ```library.json``` should also be updated to v0.9.7

**Comment by GreyGnome** [comment]
Yes I'm working on that. I will release 0.9.8 soon.

**Pull request merged**
